name: Random Pulse Commit

on:
  schedule:
    - cron: "0 10 * * *"  # 10 AM UTC
  workflow_dispatch:

jobs:
  pulse_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
    mkdir -p logs
          git config --global user.name "nosense00-bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Generate Random Commit Message
        run: |
    mkdir -p logs
          MESSAGES=("pulse: Gotchipus summon" "update: soul bond" "chore: activity refresh" "fix: summon update" "refactor: evolution logs" "data: summon sync")
          MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          echo "$(date) - $MSG" >> activity-sync.txt
          git add activity-sync.txt
          git commit -m "$MSG" || echo "No changes" || echo "No changes to commit" || echo "No changes, skipping commit"

      - name: Push Commit
        run: git push origin main
